# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6274b75f81bee1cb1318e39cb03d4b6b73eecd701bc046e6d0de0a15ea0598e0db63e6e98e6be412e611bddb18a44a94c2fd758cf58ba542555368147f4e4a6f

test:
  secret_key_base: 84aeb0c2a6bb7c3ebf6d7c337ebefad052f9ffee1e5241eb34711462c885ac1a4a879636c62741a0e58c172e578ebe3ce2294105522a707c0e547b19e1d9dcb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
